title: Your awesome title 
theme: minima
author: Kian Hibe         
email: kian.hibe@protonmail.com
description: > # this means to ignore newlines until "baseurl:"
 Going through the GitHub Pages course in Learning Lab
              
# social links
github_username:  KenAmaya # DO NOT include the @ character, or else the build will fail!
  
show_excerpts: true # set to false to remove excerpts on the homepage

